ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APPUSER;

CREATE TABLE tickets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    description VARCHAR2(1000) NOT NULL,
    status VARCHAR2(50) DEFAULT 'PENDING' NOT NULL,
    ai_category VARCHAR2(100),
    ai_priority VARCHAR2(50),
    ai_summary VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE PROCEDURE sp_update_ticket_ai (
    p_ticket_id IN NUMBER,
    p_category IN VARCHAR2,
    p_priority IN VARCHAR2,
    p_summary IN VARCHAR2
)
AS
BEGIN
    UPDATE tickets
    SET ai_category = p_category,
        ai_priority = p_priority,
        ai_summary = p_summary,
        status = 'ANALYZED'
    WHERE id = p_ticket_id;

    COMMIT;
END;
/